<a href="https://colab.research.google.com/github/krzysztof-ui/data-sceince-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'2.1.3'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [8]:
x = np.array([1,3])
print(x)

[1 3]


In [9]:
type(x)

numpy.ndarray

In [14]:
x.ndim   # Wymiar tablicy

1

In [15]:
x.shape  # Kształt tablicy

(2,)

In [16]:
x.size # liczba elementów w tablicy

2

In [17]:
x.dtype # typ danych w tablicy

dtype('int64')

In [19]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [20]:
x.dtype

dtype('float64')

In [24]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [25]:
x.ndim

2

In [26]:
x.shape

(2, 2)

In [27]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [28]:
x.shape

(2, 3)

In [32]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

     [[4, 1, 3],
      [4, 2, 1]],

     [[3, 2, 1],
      [4, 3, 2]]]

)

x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [33]:
x.ndim

3

In [34]:
x.shape

(3, 2, 3)

In [35]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [37]:
A = np.array([1.0, 2.3, 3,3])
A.dtype

dtype('float64')

In [39]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [41]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [45]:
A = np.array([1.0, 2.7, 3.3], dtype='int')
A.dtype

dtype('int64')

In [46]:
A

array([1, 2, 3])

In [47]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [52]:
A = np.array([24, 120, 125], dtype=np.int8)
A.dtype

dtype('int8')

In [53]:
A = np.array([24, 120, 125], dtype=np.uint8)
A.dtype

dtype('uint8')