<a href="https://colab.research.google.com/github/krzysztof-ui/data-sceince-bootcamp/blob/main/Generowanie_liczb_pseudolosowych.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
np.random.seed(0)

In [4]:
np.random.randn() # Losowa wartość z rozkładu normalnego

1.764052345967664

In [5]:
np.random.randn(10) # 10 losowych liczb z rozkładu normalnego

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [6]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [7]:
np.random.rand() # Zwraca liczbę losową z przedziału od 0 do 1

0.1965823616800535

In [8]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [9]:
np.random.rand(10, 2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [10]:
np.random.randint(10)

3

In [12]:
np.random.randint(low=10, high=101)

56

In [13]:
np.random.randint(low=10, high=101, size=10)

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [17]:
np.random.choice([4, 2, 1,3, 5])

np.int64(4)

In [18]:
np.random.choice(['python', 'java', 'sql'])

np.str_('sql')

In [21]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.random.shuffle(data)

In [24]:
data # Funkcja shuffle() miesza elementy w obiekcie data nie trzeba tworzyć nowej zmiennej

array([1, 0, 5, 2, 9, 7, 4, 6, 8, 3])