<a href="https://colab.research.google.com/github/krzysztof-ui/data-sceince-bootcamp/blob/main/Indeksowanie%2C_wycinanie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [3]:
A[2]

np.int64(2)

In [4]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [5]:
A[:2]

array([0, 1])

In [6]:
A[[0, 2]]

array([0, 2])

In [7]:
A[-1]

np.int64(19)

In [8]:
A[10:15]

array([10, 11, 12, 13, 14])

In [11]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
A[:, -1] # wycina kolumnę

array([ 4,  9, 14, 19])

In [16]:
A[1, 1]

np.int64(6)

In [18]:
A[1, 3]

np.int64(8)

In [20]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [24]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])