<a href="https://colab.research.google.com/github/krzysztof-ui/data-sceince-bootcamp/blob/main/podstawowe_operacje_na_tablicach.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [3]:
A + B

array([6, 0, 7, 4])

In [4]:
A - B

array([0, 2, 1, 0])

In [5]:
A * B

array([ 9, -1, 12,  4])

In [6]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [10]:
np.add(A, B)  # Metoda add() dodaje tablice do siebie

array([6, 0, 7, 4])

In [7]:
A + 3

array([6, 4, 7, 5])

In [8]:
2 * A

array([6, 2, 8, 4])

In [9]:
A + 3 * B

array([12, -2, 13,  8])

In [12]:
np.subtract(A, B) # Metoda subrtact() odejmuje tablice

array([0, 2, 1, 0])

In [13]:
np.multiply(A, B) # Metoda multiply() mnoży tablice

array([ 9, -1, 12,  4])

In [14]:
np.divide(A, B) # Metoda divide dzieli tablice

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [19]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [17]:
X * Y

array([[6, 0],
       [2, 0]])

In [20]:
np.dot(X, Y) # Mnożenie macieżowe dwóch macierzy

array([[  3,   6],
       [-12,   0]])

In [21]:
X.dot(Y) # Mnożenie macierzowe dwóch macierzy

array([[  3,   6],
       [-12,   0]])

In [22]:
Y.dot(X) # Mnozenie macierzy nie jest przemienne

array([[ 6, 18],
       [-5, -3]])

In [23]:
X @ Y # Inny sposób mnożenia macierzowego

array([[  3,   6],
       [-12,   0]])